Numpy Arrays

In [92]:
import numpy as np 


In [93]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [94]:
a = np.array([1,2,3,4])

In [95]:
b = np.array([1 , 0.5, 5.1, 6])

In [96]:
a[0], a[1]



(np.int64(1), np.int64(2))

In [97]:
a[0:]


array([1, 2, 3, 4])

In [98]:
a[0:2]

array([1, 2])

In [99]:
a[2:-2]
#This states that start from two index and stop before last two elements 


array([], dtype=int64)

In [100]:
a[2:]


array([3, 4])

In [101]:
a[:3]


array([1, 2, 3])

In [102]:
a[::2
  ]

array([1, 3])

In [103]:
b[0]


np.float64(1.0)

The differences between the two arrays is that one is of int and the other is of float. Numpy automatically terms the array a float if any of its element is an array.


In [104]:
b[0], b[1], b[-1]

(np.float64(1.0), np.float64(0.5), np.float64(6.0))

In [105]:
b[[0,1,-1]]

array([1. , 0.5, 6. ])

The above two does the same thing. Its all about extracting the right index element from the array.


Array Types

In [106]:
a

array([1, 2, 3, 4])

In [107]:
a.dtype


dtype('int64')

In [108]:
b.dtype

dtype('float64')

In [109]:
b

array([1. , 0.5, 5.1, 6. ])

In [110]:
np.array([1,2,3,4],dtype=np.float64)
# NOTE: np.float is deprecated as of NumPy 1.20.
# It was just an alias for the built-in float, not a true NumPy type.
# Use `float` or `np.float64` instead to avoid errors and ensure clarity.
# This cleanup was done to reduce confusion and align with Python's native types.

array([1., 2., 3., 4.])

In [111]:
c = np.array(["a","b","c"])

In [112]:
c.dtype

dtype('<U1')

Numpy stores data that is homogeneous that is of the similar type. We can store data in a structured array that stores structured records that mimics a key value pair like array. Its only preffered when you want to achieve the numpys speed.

In [113]:
#Dimensions and Shapes 
d = np.array([[1,2,3],
             [4,5,6]])
#Simply creating a numpy array with 2 rows and three columns

In [114]:
print(d)

[[1 2 3]
 [4 5 6]]


Why do we need arrays with different dimensions?

1. To represent different types of data structures naturally
	•	1D arrays — like lists or vectors
Example: A list of temperatures for a week [23, 25, 20, 22]
	•	2D arrays — like tables or matrices
Example: A spreadsheet of students’ grades (rows = students, columns = subjects)
	•	3D arrays and higher — more complex data like:
	•	A video (sequence of images: time × height × width × color channels)
	•	A stack of images or 3D medical scans (height × width × depth)
	•	Multi-channel sensor data collected over time

2. To match real-world data complexity

Many real-world datasets are inherently multidimensional:
	•	Images: 2D (height × width) or 3D with color channels (height × width × 3)
	•	Videos: 4D (frames × height × width × channels)
	•	Geospatial data: latitude × longitude × time
	•	Scientific measurements: sensors × time × trials

3. Efficient computation and memory layout

Multidimensional arrays allow libraries like NumPy to:
	•	Store data compactly in memory
	•	Perform vectorized operations efficiently (e.g., matrix multiplication, convolutions)
	•	Use specialized algorithms that rely on data structure shape


4. To use mathematical models and algorithms

Many algorithms require data in specific dimensions:
	•	Linear algebra uses matrices (2D arrays)
	•	Machine learning models often expect tensors (3D or higher)
	•	Deep learning frameworks use high-dimensional arrays (tensors) for input/output


Notes : Tensor refers to multidimensional arrays of any shape. It is also reffered as ranks or orders
	•	A scalar (single number) is a 0D tensor.
	•	A vector (1D array) is a 1D tensor.
	•	A matrix (2D array) is a 2D tensor.
	•	A 3D array is a 3D tensor.
	•	And so on…

Understanding how numpy works with real world data 

How natural data gets represented as arrays (vectors, matrices, tensors):

1. Everything gets digitized and broken down into numeric components

Computers don’t “see” images or videos like we do — they only understand numbers. So, to represent real-world data:
	•	Images are broken down into pixels — each pixel is a numeric value (e.g., grayscale brightness from 0 to 255, or RGB color channels)
	•	Videos are sequences of images (frames), so they become stacks of matrices (frames × height × width × color channels)
	•	Audio is sampled at discrete points in time — turning sound waves into sequences of numbers (1D arrays or 2D if stereo)
	•	Text is converted into numbers via encoding schemes (e.g., ASCII codes or embeddings)


2. Dimensions arise naturally from the structure of the data
	•	Vectors (1D arrays): Single lists of numbers — like a list of temperatures, or audio samples over time
	•	Matrices (2D arrays): Tables or grids — like images (height × width), spreadsheets (rows × columns)
	•	Tensors (3D+ arrays): Data with more complex structure — color images have 3 channels (height × width × 3), videos add a time dimension (frames × height × width × channels)


3. Why numbers? Because numbers are the universal language of computation
	•	Numbers allow us to represent intensity, color, frequency, or any measurable attribute precisely
	•	Computers manipulate numbers quickly and accurately
	•	Using arrays (vectors, matrices, tensors) lets us model relationships and patterns in data efficiently (e.g., neighbor pixels in images)


4. How this mapping actually works — a simple example

Image → digital photo:
	•	A 100×100 pixel grayscale image becomes a 2D array with shape (100, 100)
	•	Each element is a number between 0 (black) and 255 (white)

Video:
	•	A 30-second video at 30 frames per second is 900 frames
	•	Each frame is a 2D (grayscale) or 3D (color) array
	•	So the video is a 4D tensor (900, height, width, channels)


5. Advanced numeric representations
	•	For text, techniques like word embeddings convert words into numeric vectors in high-dimensional space
	•	For sound, spectrograms transform audio into 2D images representing frequency over time

In [115]:
#numpy attributes and function 
d.shape

(2, 3)

In [116]:
d.ndim
#If you call something that is not a function it will give you with an error that says the object is not callable which was returned when I called d.ndim() which is not right

2

In [117]:
d.size
#return you with the total number of elements 


6

In [118]:
e = np.array(
    [[[1,2,3],[4,5,6]],
     [[7,8,9], [0,1,2]]])

#What i figured out here is that to know the dimensions of an array, you can see the total number of "[" this bracket in the front two know its dimension
#Its not a perfect way but it works for me.

In NumPy, the shape of an array tells you how many elements exist along each dimension. It’s written as a tuple like (x, y, z) where:
	•	x → number of blocks (1st dimension)
	•	y → number of rows in each block (2nd dimension)
	•	z → number of columns in each row (3rd dimension)


In [119]:
e  

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [120]:
f = np.array([
    [[2, 4],
     [5, 6]],
    [[6, 7]]
])

#Matching the shape consistent is very important other wise it will result us with an error. 
#error: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [121]:
#Indexing and slicing matrix
h = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [122]:
#Indexing
h[2,2]
#Give me the element at row index 2 and column index 2 from the array h.

np.int64(9)

In [123]:
#Slicing
h[1:,1:]


array([[5, 6],
       [8, 9]])

When slicing you can slice it based on the dimension of it. So. what I meant is that a 2D array is a matrix having two axis. One is for the rows and other is for the columns. So when you slice it. First slices the rows other slcies the column so at last you end up with what has been sliced. When slicing it is differntiated using the sign ":". The left hand side represents the start and right hand represents the end.If omitted or no values are passed, it defaults to the beginning (start) or the end (stop) The start is inclusive and the end is exclusive. So in the above code what i am doing is that start at the row that is 1 inclusively till last. If the end is not given it refers all. And for the columns as well start at 1 inclusively till last. SO this will result the sliced array.

In [125]:
#Indexing and slicing multiodimensional array
g = np.array([[
                [1,2,3],
                [4,5,6],
                [7,8,9]
                ],
               [
                [1,2,3],
                [4,5,6],
                [9,8,0]
               ],
               [
                [4,5,6],
                [7,8,9],
                [8,4,3]
                ]
                ])

In [126]:
g.shape

(3, 3, 3)

In [127]:
#Slicing of a multidimensional array
g[2:,2:,:]
# "Give me all elements from:
#  • Layer 2 onwards (axis 0),
#  • Row 2 onwards within those layers (axis 1),
#  • And all columns of those rows (axis 2)."

array([[[8, 4, 3]]])

In [128]:
#Indexing of a multidimensional array
g[1][2][1]

np.int64(8)

Now, through my research what i have found is that the generalized term for all the things we have been learning here in our numpy session are called tensor. 
Scalar is a 0D tensor. When scalar is stacked then we form a vector that is a 1D tensor. And when a vector is stacked we form a matrix that is a 2D tensor. And when matrix is stacked we form a 3D tensor that is referred as a multidimensional array. And stacking n dimensional tensor forms another tensor of the shape (n,b,r,c) where n is the dimension, b is blocks, r is row and c is column. If dimensions seems confusing then you can refer dimensions as a number of axes or level of indexing. So to get a certain elements in a 3D array. We will have to access it with indexing like A[1,2,3] to get that specific element. So to get that very element we had to go through 3 levels of indexing. First for the block, second for the rows and last for the columns. So this level of indexing can be termed as a dimension. If axes is what confuses you then axes is simply a collection of axis. And axis refer to the one direction. So simply putting all together axes is a colletion of different directions. 2D arrays has two direction one for the row other for the column. And 3D arrays has three direction that is rows, columns and the depth that refers to layers. And layers are simply total stacks of the lower tensors. 

In [129]:
g

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [9, 8, 0]],

       [[4, 5, 6],
        [7, 8, 9],
        [8, 4, 3]]])

In [130]:
g[1] = [[4,5,6],
        [7,8,9],
        [1,2,3]]
#If the shapes match then we can replcae the layers or any rows or columns in need

In [131]:
g

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[4, 5, 6],
        [7, 8, 9],
        [1, 2, 3]],

       [[4, 5, 6],
        [7, 8, 9],
        [8, 4, 3]]])

In [132]:
g[1,2] = [0,0,0]

In [133]:
g

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[4, 5, 6],
        [7, 8, 9],
        [0, 0, 0]],

       [[4, 5, 6],
        [7, 8, 9],
        [8, 4, 3]]])

In [134]:
g[2] = 1
#This changes the overall elements of the respective index to  1. For now the index 2 layers elements will all be 1



In [135]:
g

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[4, 5, 6],
        [7, 8, 9],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [136]:
#Summary statistics we can do with numpy
#This works for every tensors
g.sum()

np.int64(93)

In [137]:
g.mean()

np.float64(3.4444444444444446)

In [138]:
g.std()

np.float64(3.010270485365348)

In [139]:
g.var()

np.float64(9.06172839506173)

In [140]:
g.sum(axis=0)

array([[ 6,  8, 10],
       [12, 14, 16],
       [ 8,  9, 10]])

In [141]:
g.sum(axis=1)

array([[12, 15, 18],
       [11, 13, 15],
       [ 3,  3,  3]])

In [142]:
g.sum(axis=2)

array([[ 6, 15, 24],
       [15, 24,  0],
       [ 3,  3,  3]])

In [143]:
g.max()

np.int64(9)

In [144]:
g[1].max()

np.int64(9)

In [145]:
g.min()

np.int64(0)

Broadcasting and Vectorized Operations

Vectorization

Vectorization is the process of replacing explicit loops with array operations for faster and clear execution. 
Numpy uses C code behind the scenes to perform operations on a large numbers of data at once compared to python which relies on loop. 
Numpys backend is written in C.

Broadcasting 
Broadcasting refers to the process of performing math operation on array of different shape where the smaller arrays are automatically matched in shape to perform different operation. For example if you have one big array with 5 elements of 2 and one small array with only one element that is 2. If you want to add these arrays. Numpy considers the single element array to be a array with 5 elements like that of the bigger array so that operations become faster. It will automatically stretch the smaller array to match the bigger ones.

In [146]:
A = np.arange(4)
A

array([0, 1, 2, 3])

arange is a function that takes four params that is start,stop,step and dtypes. So when a single params is passed its considered as a stop and the number starts from 0. If you want to reshape to a different dimension then first you create a !D array and later reshape it to the respective shape giving the rows and column parameters to the reshape function.

In [ ]:
reshaped = A.reshape(2,2)
reshaped
#The values of A were updated when i run the code below since i added this info later the value has changed but the logic of reshaping remains the same.

array([[115, 116],
       [117, 118]])

In [147]:
A + 10
#Example of Vectorized addition using broadcasting  
#Same 10 is added to all the elements of the A without the use of loop. Shape are matched to the bigger one.

array([10, 11, 12, 13])

In [ ]:
A * 10
#This wont update the A at all because we are not assigning the value at all

array([ 0, 10, 20, 30])

In [ ]:
A += 10
# This is what updates the A and its element because its the short form of A = A + 10 which reassigns the A
#The cool part of numpy is that it does not create a new array instead it gets changed in the previous location where it was saved and help preserve memory

In [150]:
A += 100

In [151]:
A

array([110, 111, 112, 113])

In [ ]:
A += 5

In [153]:
A

array([115, 116, 117, 118])

In-place operations like +=, *=, etc. are very common in NumPy when you’re working with big data or want to avoid unnecessary memory usage.


In [154]:
l = [1, 2, 3, 4]
result = []
for i in l:
    result.append(i * 10)
print(result)

#Each value that passes through the for loop is added to the empty list.

[10, 20, 30, 40]


In [155]:
result

[10, 20, 30, 40]

In [156]:
l

[1, 2, 3, 4]

In [ ]:
l += 10
#l += something means: “add each element from something into l”. Python wants it to be a list or a tuple so that it can add the corresponding elements one by one by iterating on it one by one but 10 is not iterable.

TypeError: 'int' object is not iterable

In [158]:
l = [i + 10 for i in l]
print(l)

[11, 12, 13, 14]


In [ ]:
l + 10
#Only list can be added to a list. Since 10 is just a number it cannot be concatenated

TypeError: can only concatenate list (not "int") to list

In [ ]:
l1 = [1,2,3,4]
l2 = [5,6]
l1+l2
#example of a concatenation between two lists 

[1, 2, 3, 4, 5, 6]

When we added 10 to a NumPy array, it added 10 to each element using vectorized addition enabled by broadcasting. But for the above list its not possible because although it looks like a numpy array it is a list of a python.

In [164]:
B = np.array([10,10,10,10])

In [165]:
A + B

array([125, 126, 127, 128])

In [166]:
A * B

array([1150, 1160, 1170, 1180])

In [178]:
a = np.arange(5)

In [179]:
a+5

array([5, 6, 7, 8, 9])

Boolean Arrays (Very very important)

In [182]:
C = np.arange(5)

In [184]:
C

array([0, 1, 2, 3, 4])

In [ ]:
C[[0,-1]]
#Accesing the specific index elements(multi index way)

array([0, 4])

In [ ]:
C[0],C[-1]
#Second way to access specific index elements (regular python way)

(np.int64(0), np.int64(4))

In [ ]:
#This is a new way than the above using boolean param (boolean way)
C[[True,False,False,False,True]]

array([0, 4])

All of the above accesses the specific index elements but in their own ways.

In [ ]:
D = np.arange(2,3)
#Here 2 and 3 are not the rows and columns but are the start and the stop where stop is exclusive
D

array([2])

In [ ]:
C <= 2
#Broadcating boolean operators 
#[0, 1, 2, 3, 4] <= [2, 2, 2, 2, 2]  this is what happens during the broadcasting


array([ True,  True,  True, False, False])

In [ ]:
#Combining these operations now we get
C[C<=2]
#Read this as: From array C, give me only the elements that are less than or equal to 2.
#The advantage we get out of this is filtering numerous datas.

array([0, 1, 2])

In [197]:
C.mean()
#This gives us the mean of all the data.

np.float64(2.0)

In [198]:
#Now with this boolean arrays filtration we can extract different datas that matches our condition
C[C <= C.mean()]

array([0, 1, 2])

In [ ]:
C[~(C <= C.mean())]
# "~" this acts as a not operator

array([3, 4])

In [ ]:
C[(C == 0) | (C == 1)]
# "|" this acts as an OR operator which gives elements that satisfies one of the condition

array([0, 1])

In [ ]:
C[(C == 0) & (C < 1)]
# "&" this AND Operator which gives the elements that satisfies both the condition

array([0])

In [203]:
#Another use of the AND Operator
C[(C <= 2) & (C % 2 == 0)]

array([0, 2])

In [207]:
A = np.random.randint(100, size = (3,3))
A

array([[98, 49, 26],
       [ 7, 77, 89],
       [33, 27, 14]])

Numpys randint function 
np.random.randint(low, high=None, size=None, dtype=int)
These are the parametes that randint function accepts. 

If only one number is passed to np.random.randint(), it’s treated as the high value, and low defaults to 0. If size is not provided, it returns a single random integer instead of an array. Although randint implies the output is integers, the dtype lets you control the exact integer type (like int32, int64, etc.) for memory or precision needs — the int in randint just means “generate integers”, not a fixed type.

As a data scientist, you often need to test things before using real-world data. Random data helps you practice, test models, or fill in gaps when data is missing or unbalanced. For example, if you have 1,000 happy customers and only 50 unhappy ones, you can create more “fake” unhappy ones using random patterns to help your model learn better. It’s like using a realistic dummy for training before handling the real thing — it makes your models more reliable and fair.

Its very important because it lets you quickly generate realistic test data, simulate different scenarios, or balance datasets — all without needing real data at first.


In [208]:
A[[True, False , True],
  [True, False , True],
  [True, False , True]]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In the above code the problem is that we are multiindexing the values so that is why since it is a 2D array we are indexing a 3D array for now. So it return Index error

In [ ]:
row_mask = [True , False, True]
column_mask = [True, False, True]

selected = A[np.ix_(row_mask,column_mask)]
print(selected)


[[98 26]
 [33 14]]


np.ix_() is used to combine row and column masks or indices properly so that NumPy knows you want to select a grid of values — not individual elements using multi-indexing.

Without np.ix_, Python might interpret the row and column lists as trying to fetch specific coordinates, like A[0, 2], which can cause confusion or errors in 2D arrays.

So, np.ix_ helps NumPy generate the correct 2D indexing structure, ensuring it selects rows and columns as expected, not as separate element positions.


In [212]:
A


array([[98, 49, 26],
       [ 7, 77, 89],
       [33, 27, 14]])

In [213]:
#Filtering specific data
A[np.array([
    [True, True, False],
    [False, True, True],
    [True, False, False],
    
])]

array([98, 49, 77, 89, 33])

In [215]:
A > 27

array([[ True,  True, False],
       [False,  True,  True],
       [ True, False, False]])

In [217]:
#Perfect approach and the best alternative for the above data filtration as above process is time consuming and not practical
A[A>27]

array([98, 49, 77, 89, 33])

Linear Algebra

In [218]:
J = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]]
)

In [224]:
K = np.array([[
    [3,2,1],
    [6,5,4],
    [9,8,7]
]])

In [225]:
J.dot(K)
#This is a dot product

array([[[ 42,  36,  30]],

       [[ 96,  81,  66]],

       [[150, 126, 102]]])

In [227]:
J @ K
#This is a matrix multiplication 

array([[[ 42,  36,  30],
        [ 96,  81,  66],
        [150, 126, 102]]])

In [231]:
K.T
#This is a transpose of the matrix B

array([[[3],
        [6],
        [9]],

       [[2],
        [5],
        [8]],

       [[1],
        [4],
        [7]]])

In [228]:
J

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [234]:
L = np.array([
    [1,2],
    [3,4],
    [5,6]
    ])

In [235]:
L.T @ J

array([[48, 57, 66],
       [60, 72, 84]])

In [236]:
K.T @ J

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

The above error result because for the matrix multiplication to happen the column of the first matrix must be same as the row of the matrix to be multiplied

Size of Objects in Memory 

In [238]:
# An integer in python is said to be greater than 24 bytes
import sys
sys.getsizeof(5)

28

sys is a built-in Python module that provides access to some variables and functions related to the Python interpreter and its environment.

Think of it as a way to interact with the system Python is running on — like getting info about memory, the Python version, command-line arguments, and more.

In [240]:
sys.getsizeof(10**100)
#Long are even larger 

72

In [ ]:
#numpy sizes are smaller compared to the above in python
np.dtype(int).itemsize
#That mean 8 bytes each or 64-bit

8

In [242]:
np.dtype(float).itemsize

8

Lists size

In [243]:
sys.getsizeof([1])
#List size in python

64

In [ ]:
np.array([1]).nbytes
#In numpy its comparatively very small in size

8

Performance Comparisions

In [259]:
#l = list(range(1000))
#del list
l = list(range(1000))
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [ ]:
numpy_list = np.arange(1000)
numpy_list
# It uses the same memory for creating the same list again and again so running it twice wont effect the flow compared to list in python

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [266]:
%time np.sum(numpy_list ** 2)

CPU times: user 59 μs, sys: 5 μs, total: 64 μs
Wall time: 68.2 μs


np.int64(332833500)

In [267]:
%time sum(x ** 2 for x in l)

CPU times: user 256 μs, sys: 28 μs, total: 284 μs
Wall time: 334 μs


332833500

The time taken by numpy is far less than that taken by python

Useful numpy functions 

1. random

In [ ]:

np.random.random(size=2)

array([0.74115263, 0.65104988])

In [269]:
np.random.normal(size=2)

array([-1.33798915,  0.38599906])

In [270]:
np.random.randint(2, 4)

3

2. arange

In [272]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [274]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [275]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

3. reshape

In [276]:
np.arange(4).reshape(2,2)

array([[0, 1],
       [2, 3]])

In [277]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4. linspace

5. zeros, ones, empty

6. identity and eye